project:
  type: book

book:
  title: "Contemporary Computational Methods for Hospitality and Tourism"
  subtitle: "With Practical Examples in R"
  author: "Francisco J. Navarro"
  date: "10/16/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

